# 项目名称
project_name: V2ray_Heal
# 端口
port: :21310
# 刷新时间间隔 单位:分钟
refresh_time_interval: 15
# https配置
https:
  # 是否开启https
  enable: false
  # 证书路径
  crt_path: ./crt.crt
  key_path: ./key.key