name: ddgksf2013-M3U8LIST-sync.yml
on:
  schedule:
    - cron: '1 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-ddgksf2013-M3U8LIST
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync ddgksf2013-M3U8LIST
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/ddgksf2013/M3U8LIST.git"
          source_branch: "master"
          destination_branch: "ddgksf2013-M3U8LIST"
          github_token: ${{ secrets.PAT }}
      
